services:
  - type: web
    name: portfolio
    env: python
    rootDir: portfolio
    buildCommand: pip install -r requirements.txt
    startCommand: python -m flask run --host=0.0.0.0 --port=$PORT
    envVars:
      - key: FLOWISE_API_URL
        sync: false
      - key: FLOWISE_API_KEY
        sync: false
      - key: PYTHONPATH
        value: /opt/render/project/src/portfolio
